// SPDX-License-Identifier: MIT

package controlplane

// Daemon config snapshot. The "what is this daemon actually running
// with?" command. Today the answer is scattered across the kernel's
// startup log, ad-hoc grepping for AGEZT_*, and inferring paths
// from the OS user-home — none of which are scriptable. CmdConfig
// gives operators (and CI smoke tests) one round-trip that returns
// the resolved view.
//
// Privacy: env-var VALUES are never returned. The handler reports
// only PRESENCE — `{ "AGEZT_VAULT_PASSPHRASE": true }` when the
// var is set, omitted when unset. Same rule for the system prompt:
// `system_prompt_set: bool` reports whether one is configured but
// never echoes its content (could contain proprietary instructions).

import (
	"net"
	"os"
	"path/filepath"
)

// configEnvVars is the canonical set of AGEZT_* env vars the daemon
// reads at startup. Surface PRESENCE only; the values can contain
// secrets (passphrases) or noisy details (catalog URLs that include
// auth in path). Sorted so the response key order is stable for
// snapshot tests.
//
// Source-of-truth: every Getenv("AGEZT_...") in cmd/agezt/ (plus the
// daemon's kernel/plugin reads). New vars MUST be added here when
// introduced — TestConfigEnvVars_CoversCmdAgeztReads (M127) enforces
// this by scanning cmd/agezt and failing if any read var is absent,
// so the inventory can no longer silently rot.
var configEnvVars = []string{
	"AGEZT_ACP_AGENT_CMD",
	"AGEZT_ALERT_NOTIFY",
	"AGEZT_ALERT_NOTIFY_COOLDOWN",
	"AGEZT_ALERT_NOTIFY_LEVEL",
	"AGEZT_ALERT_NOTIFY_MAX",
	"AGEZT_ALERT_NOTIFY_MUTE",
	"AGEZT_ALERT_NOTIFY_MUTE_SOURCES",
	"AGEZT_ALLOW_ALL",
	"AGEZT_ANOMALY_MAX_TOOLCALLS",
	"AGEZT_ANOMALY_WINDOW",
	"AGEZT_API_ADDR",
	"AGEZT_APPROVAL_MODE",
	"AGEZT_APPROVAL_TIMEOUT",
	"AGEZT_ARTIFACT_THRESHOLD",
	"AGEZT_AUTO_REPAIR",
	"AGEZT_AUTO_REPAIR_COOLDOWN",
	"AGEZT_ROUTING_ROLLBACK_PROBATION",
	"AGEZT_ROUTING_FORCE_PROBATION",
	"AGEZT_ROUTING_PRESSURE_THRESHOLD",
	"AGEZT_ROUTING_PRESSURE_WINDOW",
	"AGEZT_ROUTING_UNSTABLE_THRESHOLD",
	"AGEZT_ROUTING_UNSTABLE_WINDOW",
	"AGEZT_AUTO_CONTINUE_WAIT",
	"AGEZT_AWS_ASSUME_ROLE_ARN",
	"AGEZT_AWS_ASSUME_ROLE_DURATION_SECONDS",
	"AGEZT_AWS_ASSUME_ROLE_EXTERNAL_ID",
	"AGEZT_AWS_ASSUME_ROLE_SESSION_NAME",
	"AGEZT_AWS_SSO_PROFILE",
	"AGEZT_BRAIN_DISTILL_EVERY",
	"AGEZT_BROWSER_ALLOWED_HOSTS",
	"AGEZT_BROWSER_ALLOW_ALL",
	"AGEZT_BROWSER_ALLOW_LOOPBACK",
	"AGEZT_BROWSER_ALLOW_PRIVATE",
	"AGEZT_BROWSER_COOKIES",
	"AGEZT_CANCEL_ON_DISCONNECT",
	"AGEZT_CATALOG_URL",
	"AGEZT_CHANNEL_HISTORY",
	"AGEZT_CODING_CMD",
	"AGEZT_CONFIG",
	"AGEZT_CONTEXT_BUDGET",
	"AGEZT_CONTEXT_PROTECT_FIRST",
	"AGEZT_CONTEXT_SUMMARIZE",
	"AGEZT_COUNCIL_MEMBERS",
	"AGEZT_DEFAULT_CHAIN",
	"AGEZT_DEMO_ECHO",
	"AGEZT_DISCORD_ADDR",
	"AGEZT_DISCORD_API_BASE",
	"AGEZT_DISCORD_APP_ID",
	"AGEZT_DISCORD_CHANNELS",
	"AGEZT_DISCORD_PUBLIC_KEY",
	"AGEZT_DISCORD_TOKEN",
	"AGEZT_DRAIN_TIMEOUT",
	"AGEZT_EDICT_DENY",
	"AGEZT_EDICT_DURABLE",
	"AGEZT_EMAIL_FROM",
	"AGEZT_EMAIL_PASSWORD",
	"AGEZT_EMAIL_RECIPIENTS",
	"AGEZT_EMAIL_SMTP_ADDR",
	"AGEZT_EMAIL_USERNAME",
	"AGEZT_EMAIL_INBOX_ADDR",
	"AGEZT_EMAIL_INBOX_PROTOCOL",
	"AGEZT_EMAIL_INBOX_USERNAME",
	"AGEZT_EMAIL_INBOX_PASSWORD",
	"AGEZT_EMAIL_INBOX_TLS",
	"AGEZT_EMAIL_INBOX_POLL",
	"AGEZT_EMBED_KEY",
	"AGEZT_EMBED_MODEL",
	"AGEZT_EMBED_URL",
	"AGEZT_IMAGE_KEY",
	"AGEZT_IMAGE_MODEL",
	"AGEZT_IMAGE_URL",
	"AGEZT_RERANK_KEY",
	"AGEZT_RERANK_MODEL",
	"AGEZT_RERANK_URL",
	"AGEZT_GEN_TEMPERATURE",
	"AGEZT_GEN_TOP_P",
	"AGEZT_GEN_REASONING_EFFORT",
	"AGEZT_EXTRACT_REASONING",
	"AGEZT_SIMULATE_STREAMING",
	"AGEZT_ENV_INJECT",
	"AGEZT_EPISTEMIC_ESCALATION",
	"AGEZT_FALLBACK_CHAINS",
	"AGEZT_FORCE_START",
	"AGEZT_FORGE",
	"AGEZT_GRAVEYARD_RETENTION_DAYS",
	"AGEZT_GOOGLECHAT_WEBHOOK",
	"AGEZT_GOOGLECHAT_ADDR",
	"AGEZT_GOOGLECHAT_TOKEN",
	"AGEZT_GOOGLECHAT_USERS",
	"AGEZT_GOOGLECHAT_PATH",
	"AGEZT_GOTIFY_SERVER",
	"AGEZT_GOTIFY_TOKEN",
	"AGEZT_HOME",
	"AGEZT_INTENT_REGRET_GATING",
	"AGEZT_DISABLE_HEURISTIC_BYPASS",
	"AGEZT_HOMEASSISTANT_SERVICES",
	"AGEZT_HOMEASSISTANT_TOKEN",
	"AGEZT_HOMEASSISTANT_TOOL_ALLOW_ALL_SERVICES",
	"AGEZT_HOMEASSISTANT_TOOL_READ",
	"AGEZT_HOMEASSISTANT_TOOL_SERVICES",
	"AGEZT_HOMEASSISTANT_URL",
	"AGEZT_HTTP_ALLOWED_HOSTS",
	"AGEZT_HTTP_ALLOW_ALL",
	"AGEZT_HTTP_ALLOW_LOOPBACK",
	"AGEZT_HTTP_ALLOW_PRIVATE",
	"AGEZT_LLM_CACHE_TTL",
	"AGEZT_MATRIX_HOMESERVER",
	"AGEZT_MATRIX_ROOMS",
	"AGEZT_MATRIX_TOKEN",
	"AGEZT_MATTERMOST_WEBHOOK",
	"AGEZT_MATTERMOST_ADDR",
	"AGEZT_MATTERMOST_TOKEN",
	"AGEZT_MATTERMOST_USERS",
	"AGEZT_MATTERMOST_PATH",
	"AGEZT_MAX_AUTO_CONTINUE",
	"AGEZT_MAX_ITER",
	"AGEZT_MEMORY",
	"AGEZT_MEMORY_DISTILL_MIN_TOOLS",
	"AGEZT_MESH_MAX_HOPS",
	"AGEZT_MODEL",
	"AGEZT_MODEL_DOWNROUTE",
	"AGEZT_MODEL_DOWNROUTE_CROSS",
	"AGEZT_MODEL_STRICT",
	"AGEZT_MULTITENANT",
	"AGEZT_OBSERVATION_DELTAS",
	"AGEZT_NTFY_SERVER",
	"AGEZT_NTFY_TOKEN",
	"AGEZT_NTFY_TOPIC",
	"AGEZT_OLLAMA_ENDPOINT",
	"AGEZT_OVERSEER_FLEET_LOCK",
	"AGEZT_PARALLEL_TOOLS",
	"AGEZT_PEERS",
	"AGEZT_PLUGINS",
	"AGEZT_PLUGIN_PINS",
	"AGEZT_PLUGIN_TOOLS",
	"AGEZT_PRICING_STRICT",
	"AGEZT_PROMPT_INJECTION_GUARD",
	"AGEZT_PROVIDER",
	"AGEZT_PULSE",
	"AGEZT_PULSE_CADENCE",
	"AGEZT_PULSE_DIAL",
	"AGEZT_PULSE_DISK",
	"AGEZT_PULSE_HEALTH",
	"AGEZT_PULSE_INITIATIVE",
	"AGEZT_PULSE_LLM",
	"AGEZT_PULSE_PROBE",
	"AGEZT_PULSE_QUIET_HOURS",
	"AGEZT_RATE_PER_MIN",
	"AGEZT_REDACT",
	"AGEZT_REDACT_EXTRA",
	"AGEZT_PUSHBULLET_TOKEN",
	"AGEZT_PUSHOVER_TOKEN",
	"AGEZT_PUSHOVER_USER",
	"AGEZT_REFLECT_EVERY",
	"AGEZT_REST_ADDR",
	"AGEZT_RUN_TIMEOUT",
	"AGEZT_SANDBOX",
	"AGEZT_SANDBOX_NO_NET",
	"AGEZT_SCHEDULE",
	"AGEZT_SCHEDULE_NOTIFY",
	"AGEZT_SCHEDULE_RUN_TIMEOUT",
	"AGEZT_SIGNAL_API_URL",
	"AGEZT_SIGNAL_NUMBER",
	"AGEZT_SIGNAL_POLL_SECS",
	"AGEZT_SIGNAL_RECIPIENTS",
	"AGEZT_SIGNAL_TOKEN",
	"AGEZT_SKILLS",
	"AGEZT_SKILL_AUTOPROMOTE",
	"AGEZT_SKILL_AUTOQUARANTINE",
	"AGEZT_SKILL_AUTOSHADOW",
	"AGEZT_SKILL_SHADOWEVAL",
	"AGEZT_SLACK_ADDR",
	"AGEZT_SLACK_API_BASE",
	"AGEZT_SLACK_CHANNELS",
	"AGEZT_SLACK_SIGNING_SECRET",
	"AGEZT_SLACK_TOKEN",
	"AGEZT_SMS_ACCOUNT_SID",
	"AGEZT_SMS_ADDR",
	"AGEZT_SMS_AUTH_TOKEN",
	"AGEZT_SMS_FROM",
	"AGEZT_SMS_NUMBERS",
	"AGEZT_SMS_PATH",
	"AGEZT_SMS_PUBLIC_URL",
	"AGEZT_STT_API_KEY",
	"AGEZT_STT_API_URL",
	"AGEZT_STT_MODEL",
	"AGEZT_SUBAGENT",
	"AGEZT_SUBAGENT_DEPTH",
	"AGEZT_SUBAGENT_FANOUT",
	"AGEZT_SUBAGENT_MAX_TOTAL",
	"AGEZT_SUBAGENT_SPEND_CAP",
	"AGEZT_SYSTEM_PROMPT",
	"AGEZT_TASK_BUDGETS",
	"AGEZT_TASK_MODEL_CHAINS",
	"AGEZT_TASK_MODEL_OVERRIDES",
	"AGEZT_TASK_ROUTES",
	"AGEZT_TASK_ROUTE_REQUIRES",
	"AGEZT_TEAMS_WEBHOOKS",
	"AGEZT_TELEGRAM_API_BASE",
	"AGEZT_TELEGRAM_CHAT_ID",
	"AGEZT_TELEGRAM_TOKEN",
	"AGEZT_TENANT_DAILY_CEILING",
	"AGEZT_TENANT_PEERS",
	"AGEZT_TENANT_RATE_PER_MIN",
	"AGEZT_TOKEN",
	"AGEZT_TOOL_DISCOVERY_MAX",
	"AGEZT_TOOL_TIMEOUT",
	"AGEZT_TUNNEL",
	"AGEZT_TUNNEL_CMD",
	"AGEZT_TUNNEL_TARGET",
	// Self-update (M860).
	"AGEZT_UPDATE_CHECK_INTERVAL",
	"AGEZT_UPDATE_DRAIN_TIMEOUT",
	"AGEZT_UPDATE_ENDPOINT",
	"AGEZT_UPDATE_GITHUB_OWNER",
	"AGEZT_UPDATE_GITHUB_REPO",
	"AGEZT_USER_PROFILE",
	"AGEZT_USER_PROFILE_EVERY",
	"AGEZT_VAULT_AUTOENCRYPT",
	"AGEZT_VAULT_PASSPHRASE",
	"AGEZT_VAULT_PASSPHRASE_NEW",
	"AGEZT_VOICE_RECORD_CMD",
	"AGEZT_WEBHOOKS",
	"AGEZT_WEBHOOK_ADDR",
	"AGEZT_WEBHOOK_ALLOW_LOOPBACK",
	"AGEZT_WEBHOOK_ALLOW_PRIVATE",
	"AGEZT_WEBHOOK_CHANNELS",
	"AGEZT_WEBHOOK_OUTBOUND_URL",
	"AGEZT_WEBHOOK_PATH",
	"AGEZT_WEBHOOK_SECRET",
	"AGEZT_WEB_ADDR",
	"AGEZT_WEB_ALLOWED_HOSTS",
	"AGEZT_WEB_PASSWORD",
	"AGEZT_WEB_PASSWORD_STRICT",
	"AGEZT_WHATSAPP_ACCESS_TOKEN",
	"AGEZT_WHATSAPP_ADDR",
	"AGEZT_WHATSAPP_APP_SECRET",
	"AGEZT_WHATSAPP_NUMBERS",
	"AGEZT_WHATSAPP_PATH",
	"AGEZT_WHATSAPP_PHONE_NUMBER_ID",
	"AGEZT_WHATSAPP_VERIFY_TOKEN",
	"AGEZT_WORKSPACE",
	"AGEZT_WORLDMODEL",
	// Push / webhook channels (Rocket.Chat, Mastodon, Line, Zulip).
	"AGEZT_ROCKETCHAT_WEBHOOK",
	"AGEZT_MASTODON_SERVER",
	"AGEZT_MASTODON_TOKEN",
	"AGEZT_MASTODON_USERS",
	"AGEZT_MASTODON_POLL",
	"AGEZT_LINE_TOKEN",
	"AGEZT_LINE_TO",
	"AGEZT_LINE_SECRET",
	"AGEZT_LINE_USERS",
	"AGEZT_LINE_ADDR",
	"AGEZT_LINE_PATH",
	"AGEZT_ZULIP_SERVER",
	"AGEZT_ZULIP_EMAIL",
	"AGEZT_ZULIP_APIKEY",
	"AGEZT_ZULIP_STREAM",
	"AGEZT_ZULIP_TOPIC",
	// Enterprise / Asia webhook bots.
	"AGEZT_FEISHU_WEBHOOK",
	"AGEZT_FEISHU_APP_ID",
	"AGEZT_FEISHU_APP_SECRET",
	"AGEZT_FEISHU_VERIFY_TOKEN",
	"AGEZT_FEISHU_CHAT",
	"AGEZT_FEISHU_USERS",
	"AGEZT_FEISHU_ADDR",
	"AGEZT_FEISHU_PATH",
	"AGEZT_DINGTALK_WEBHOOK",
	"AGEZT_DINGTALK_SECRET",
	"AGEZT_DINGTALK_USERS",
	"AGEZT_DINGTALK_ADDR",
	"AGEZT_DINGTALK_PATH",
	"AGEZT_WECOM_WEBHOOK",
	"AGEZT_WECOM_CORP_ID",
	"AGEZT_WECOM_CORP_SECRET",
	"AGEZT_WECOM_AGENT_ID",
	"AGEZT_WECOM_TOKEN",
	"AGEZT_WECOM_AES_KEY",
	"AGEZT_WECOM_USERS",
	"AGEZT_WECOM_ADDR",
	"AGEZT_WECOM_PATH",
	// QQ (OneBot gateway, two-way).
	"AGEZT_QQ_GATEWAY",
	"AGEZT_QQ_TOKEN",
	"AGEZT_QQ_SECRET",
	"AGEZT_QQ_USERS",
	"AGEZT_QQ_ADDR",
	"AGEZT_QQ_PATH",
	// WeChat (OneBot gateway, two-way).
	"AGEZT_WECHAT_GATEWAY",
	"AGEZT_WECHAT_TOKEN",
	"AGEZT_WECHAT_SECRET",
	"AGEZT_WECHAT_USERS",
	"AGEZT_WECHAT_ADDR",
	"AGEZT_WECHAT_PATH",
	// Zalo (Official Account, two-way).
	"AGEZT_ZALO_APP_ID",
	"AGEZT_ZALO_TOKEN",
	"AGEZT_ZALO_SECRET",
	"AGEZT_ZALO_USERS",
	"AGEZT_ZALO_ADDR",
	"AGEZT_ZALO_PATH",
	// Nextcloud Talk (bot API, two-way).
	"AGEZT_NEXTCLOUDTALK_URL",
	"AGEZT_NEXTCLOUDTALK_SECRET",
	"AGEZT_NEXTCLOUDTALK_TOKENS",
	"AGEZT_NEXTCLOUDTALK_ADDR",
	"AGEZT_NEXTCLOUDTALK_PATH",
	// Nostr (relays, two-way).
	"AGEZT_NOSTR_PRIVKEY",
	"AGEZT_NOSTR_RELAYS",
	"AGEZT_NOSTR_AUTHORS",
	"AGEZT_SYNOLOGY_WEBHOOK",
	// WhatsApp gateway (WAHA / Evolution, two-way).
	"AGEZT_WHATSAPPGW_URL",
	"AGEZT_WHATSAPPGW_BACKEND",
	"AGEZT_WHATSAPPGW_SESSION",
	"AGEZT_WHATSAPPGW_KEY",
	"AGEZT_WHATSAPPGW_NUMBERS",
	"AGEZT_WHATSAPPGW_ADDR",
	"AGEZT_WHATSAPPGW_PATH",
	"AGEZT_WHATSAPPGW_SECRET",
	// iMessage (BlueBubbles, two-way).
	"AGEZT_IMESSAGE_URL",
	"AGEZT_IMESSAGE_PASSWORD",
	"AGEZT_IMESSAGE_METHOD",
	"AGEZT_IMESSAGE_ADDRESSES",
	"AGEZT_IMESSAGE_ADDR",
	"AGEZT_IMESSAGE_PATH",
	"AGEZT_IMESSAGE_SECRET",
	// IRC (two-way).
	"AGEZT_IRC_SERVER",
	"AGEZT_IRC_NICK",
	"AGEZT_IRC_CHANNELS",
	"AGEZT_IRC_PASSWORD",
	"AGEZT_IRC_TLS",
	"AGEZT_IRC_ALLOWLIST",
	// Twitch (two-way, IRC).
	"AGEZT_TWITCH_USERNAME",
	"AGEZT_TWITCH_TOKEN",
	"AGEZT_TWITCH_CHANNELS",
	"AGEZT_TWITCH_ALLOWLIST",
	// Voice adapter (STT + TTS — OpenAI-compatible, or a native provider).
	"AGEZT_STT_PROVIDER",
	"AGEZT_STT_URL",
	"AGEZT_STT_MODEL",
	"AGEZT_STT_KEY",
	"AGEZT_TTS_PROVIDER",
	"AGEZT_TTS_URL",
	"AGEZT_TTS_MODEL",
	"AGEZT_TTS_VOICE",
	"AGEZT_TTS_KEY",
	"AGEZT_VOICE_REPLY",
}

func (s *Server) handleConfig(conn net.Conn, req Request) {
	base := s.k.BaseDir()
	paths := map[string]any{
		"base":    base,
		"journal": filepath.Join(base, "journal"),
		"state":   filepath.Join(base, "state"),
		"runtime": filepath.Join(base, "runtime"),
		"catalog": filepath.Join(base, "catalog"),
		"vault":   filepath.Join(base, "vault.json"),
	}

	env := map[string]any{}
	for _, name := range configEnvVars {
		if _, ok := os.LookupEnv(name); ok {
			env[name] = true
		}
	}

	result := map[string]any{
		"paths":             paths,
		"model":             s.k.Model(),
		"system_prompt_set": s.k.System() != "",
		"tool_count":        len(s.k.Tools()),
		"plugin_count":      len(s.k.Plugins()),
		"ask_policy":        askPolicyLabel(s.k.Edict().AskPolicy()),
		"env":               env,
	}

	// Effective routing tables (M108): surface what AGEZT_TASK_ROUTES /
	// _ROUTE_REQUIRES / _MODEL_OVERRIDES actually parsed to, so an operator can
	// confirm a rule loaded rather than reading the boot log. Only present when
	// the provider is the governor (the usual case) and a table is non-empty.
	if gov, ok := s.k.Provider().(interface {
		TaskRoutesView() map[string][]string
		TaskRouteRequiresView() map[string][]string
		TaskModelOverridesView() map[string]string
	}); ok {
		routing := map[string]any{}
		if r := gov.TaskRoutesView(); len(r) > 0 {
			routing["routes"] = stringSliceMapToAny(r)
		}
		if r := gov.TaskRouteRequiresView(); len(r) > 0 {
			routing["requires"] = stringSliceMapToAny(r)
		}
		if o := gov.TaskModelOverridesView(); len(o) > 0 {
			m := make(map[string]any, len(o))
			for k, v := range o {
				m[k] = v
			}
			routing["model_overrides"] = m
		}
		if len(routing) > 0 {
			result["routing"] = routing
		}
	}

	s.writeResp(conn, Response{ID: req.ID, Type: RespResult, Result: result})
}

func stringSliceMapToAny(in map[string][]string) map[string]any {
	out := make(map[string]any, len(in))
	for k, v := range in {
		arr := make([]any, len(v))
		for i, s := range v {
			arr[i] = s
		}
		out[k] = arr
	}
	return out
}
