// SPDX-License-Identifier: MIT

// Command sdkparity generates a conservative SDK coverage report for the native
// AGEZT REST API (/api/v1). It is intentionally static: it extracts the daemon's
// route registrations from kernel/restapi/restapi.go and checks whether each SDK
// source tree contains the corresponding route prefix.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type route struct {
	Path    string
	Dynamic bool
}

type sdk struct {
	Name       string
	Files      []string
	NativeOnly bool
}

func main() {
	outPath := flag.String("out", "", "write report to this path instead of stdout")
	checkPath := flag.String("check", "", "compare generated report to this path")
	flag.Parse()

	routes, err := extractRoutes(filepath.FromSlash("kernel/restapi/restapi.go"))
	if err != nil {
		fatal(err)
	}
	sdks := []sdk{
		{Name: "Go", Files: mustGlob("sdk/*.go"), NativeOnly: true},
		{Name: "Python", Files: mustGlob("sdk/python/agezt/*.py")},
		{Name: "TypeScript", Files: mustGlob("sdk/typescript/src/*.ts")},
		{Name: "Rust", Files: mustGlob("sdk/rust/src/*.rs")},
	}

	report, err := render(routes, sdks)
	if err != nil {
		fatal(err)
	}
	if *checkPath != "" {
		want, err := os.ReadFile(*checkPath)
		if err != nil {
			fatal(err)
		}
		if !bytes.Equal(normalize(report), normalize(want)) {
			fatal(fmt.Errorf("%s is stale; run `go run ./tools/sdkparity -out %s`", *checkPath, *checkPath))
		}
		return
	}
	if *outPath != "" {
		if err := os.WriteFile(*outPath, report, 0o644); err != nil {
			fatal(err)
		}
		return
	}
	_, _ = os.Stdout.Write(report)
}

func extractRoutes(path string) ([]route, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	re := regexp.MustCompile(`mux\.HandleFunc\("([^"]+)"`)
	matches := re.FindAllStringSubmatch(string(b), -1)
	seen := map[string]bool{}
	var out []route
	for _, m := range matches {
		p := m[1]
		if !strings.HasPrefix(p, "/api/v1/") || seen[p] {
			continue
		}
		seen[p] = true
		out = append(out, route{Path: p, Dynamic: strings.HasSuffix(p, "/")})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func mustGlob(pattern string) []string {
	files, err := filepath.Glob(filepath.FromSlash(pattern))
	if err != nil {
		fatal(err)
	}
	sort.Strings(files)
	return files
}

func render(routes []route, sdks []sdk) ([]byte, error) {
	sdkRoutes := routesForSDKCoverage(routes)

	var b strings.Builder
	b.WriteString("# SDK Parity Report\n\n")
	b.WriteString("Generated by `go run ./tools/sdkparity -out docs/SDK-PARITY.md`.\n\n")
	b.WriteString("This report statically compares daemon `/api/v1` route registrations against route strings used by the Go, Python, TypeScript, and Rust SDK source trees. It is a coverage signal, not a behavioral conformance test.\n\n")
	b.WriteString("Routes marked intentionally unsupported are implemented daemon endpoints that are excluded from SDK coverage totals because they are operational/admin surfaces, not application SDK APIs.\n\n")
	b.WriteString("Legend: ✅ route string present in SDK source; — not present / intentionally unsupported; n/a = SDK uses the local control-plane protocol instead of the REST surface.\n\n")
	b.WriteString("| Route | Kind | Go | Python | TypeScript | Rust | Notes |\n")
	b.WriteString("|---|---|---:|---:|---:|---:|---|\n")
	for _, r := range routes {
		b.WriteString("| `")
		b.WriteString(r.Path)
		b.WriteString("` | ")
		if r.Dynamic {
			b.WriteString("prefix")
		} else {
			b.WriteString("exact")
		}
		for _, s := range sdks {
			if s.NativeOnly {
				b.WriteString(" | n/a")
				continue
			}
			ok, err := sdkCovers(s.Files, r)
			if err != nil {
				return nil, err
			}
			if ok {
				b.WriteString(" | ✅")
			} else {
				b.WriteString(" | —")
			}
		}
		b.WriteString(" | ")
		b.WriteString(noteForRoute(r.Path))
		b.WriteString(" |\n")
	}
	b.WriteString("\n## Summary\n\n")
	for _, s := range sdks {
		if s.NativeOnly {
			fmt.Fprintf(&b, "- **%s**: n/a for REST route-string coverage (uses local control-plane protocol; see Go SDK tests).\n", s.Name)
			continue
		}
		covered := 0
		for _, r := range sdkRoutes {
			ok, err := sdkCovers(s.Files, r)
			if err != nil {
				return nil, err
			}
			if ok {
				covered++
			}
		}
		fmt.Fprintf(&b, "- **%s**: %d/%d SDK-intended REST routes have static source coverage.\n", s.Name, covered, len(sdkRoutes))
	}
	b.WriteString("\n## Intentionally unsupported SDK routes\n\n")
	b.WriteString("- `/api/v1/update` and `/api/v1/update/apply` are implemented REST routes, but they are operational/admin self-update endpoints. SDKs intentionally do not expose self-update helpers.\n")
	b.WriteString("\n## Behavioral conformance coverage\n\n")
	b.WriteString("The generated table above is static route-string coverage only. Behavioral parity is covered separately by SDK tests and should stay explicit when new `/api/v1` features are added.\n\n")
	b.WriteString("Current behavioral coverage includes:\n\n")
	b.WriteString("- **Python sync client** (`sdk/python/tests/test_client.py`): bearer auth, health/model response mapping, sync run body/model forwarding, provider-error preservation, streaming SSE frame parsing, run event arc retrieval, 401 errors, and tenant client behavior.\n")
	b.WriteString("- **Python mailbox client** (`sdk/python/tests/test_mailbox.py`): DM send body shape, broadcast target, help flag, inbox query encoding, ack body/errors, watch SSE mail frames, replies, messages, and topics.\n")
	b.WriteString("- **Python async client** (`sdk/python/tests/test_aio.py`): async health/models, sync-run equivalent, provider-error preservation, streaming SSE frame parsing, run event arc retrieval, 401 errors, and context-manager behavior.\n")
	b.WriteString("- **TypeScript run client** (`sdk/typescript/test/client.test.ts`): bearer auth, typed health/model response mapping, sync run body/model forwarding, APIError preservation, streaming SSE frame parsing, run event arc retrieval, 401 errors, and tenant client behavior.\n")
	b.WriteString("- **TypeScript mailbox client** (`sdk/typescript/test/mailbox.test.ts`): DM send body shape, broadcast target, help flag, inbox query encoding, ack body/errors, watch SSE mail frames, replies, messages, and topics.\n")
	b.WriteString("- **Rust REST client** (`sdk/rust/tests/client.rs`): bearer auth, tenant header transmission, typed health/models, sync run model forwarding, API error preservation, streaming SSE frame parsing, run event arc fields, mailbox send/broadcast/help, inbox query encoding, ack errors, replies/messages/topics, and watch SSE mail frames.\n")
	b.WriteString("- **Go SDK** (`sdk/*_test.go`): local control-plane request construction/parsing, runtime-file dial behavior, typed run parsing, event helper semantics, approval parsing, mailbox parsing/routing behavior, and zero-value tolerance for omitted fields. Go does not use REST route-string coverage for its primary SDK path.\n")
	b.WriteString("\n## Future conformance work\n\n")
	b.WriteString("- Keep route-string coverage and behavioral conformance separate in future reports.\n")
	b.WriteString("- When a new SDK-intended `/api/v1` feature is added, add or update behavioral tests for typed request/response shape, auth behavior, error behavior, and any streaming/event semantics before calling the feature SDK-complete.\n")
	return []byte(b.String()), nil
}

func routesForSDKCoverage(routes []route) []route {
	out := make([]route, 0, len(routes))
	for _, r := range routes {
		if intentionallyUnsupportedInSDK(r.Path) {
			continue
		}
		out = append(out, r)
	}
	return out
}

func intentionallyUnsupportedInSDK(path string) bool {
	return path == "/api/v1/update" || path == "/api/v1/update/apply"
}

func sdkCovers(files []string, r route) (bool, error) {
	needle := r.Path
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			return false, err
		}
		s := string(b)
		if strings.Contains(s, needle) {
			return true, nil
		}
		if r.Dynamic && strings.Contains(s, strings.TrimSuffix(needle, "/")) {
			return true, nil
		}
	}
	return false, nil
}

func noteForRoute(path string) string {
	switch {
	case path == "/api/v1/health":
		return "daemon health"
	case path == "/api/v1/models":
		return "model catalog"
	case path == "/api/v1/runs":
		return "blocking + streaming run creation"
	case path == "/api/v1/runs/":
		return "run event arc by correlation id"
	case strings.HasPrefix(path, "/api/v1/mailbox"):
		return "inter-agent mailbox"
	case strings.HasPrefix(path, "/api/v1/update"):
		return "admin self-update endpoint"
	default:
		return ""
	}
}

func normalize(b []byte) []byte {
	s := strings.ReplaceAll(string(b), "\r\n", "\n")
	return []byte(strings.TrimSpace(s) + "\n")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
