// SPDX-License-Identifier: MIT

// Command changelog-split parses CHANGELOG.md and materializes the planned
// split structure under CHANGELOG/. It is intentionally conservative:
// - released versions are copied as-is into per-version files,
// - the Unreleased block is split by `###` subsection,
// - subsections with M###/M#### references are bucketed into 100-wide files,
// - subsections with no M reference stay in `unreleased/current.md`.
//
// The tool supports three modes:
//
//	--dry-run   print the planned output map only (default when no write flag is set)
//	--emit      write the generated files under --out-dir
//	--verify    compare the generated files to --out-dir and fail on drift
//	--force     with --emit, also overwrite tree files the tool did not generate
//	--discard-working-set
//	            with --emit, additionally allow dropping working-set content that
//	            appears in no generated output (writes a timestamped backup first)
//
// Ownership: every tree file this tool writes carries a trailing
// `generatedSentinel` comment. --emit and --verify treat the SPLIT TREE as
// canonical (root CHANGELOG.md holds one released block; the tree holds
// v1.0.0.md, v0.1.0.md and the milestone buckets, which root cannot
// regenerate), so a file without the sentinel is never overwritten or pruned
// without --force. Verification is intentionally NOT ownership-gated: reporting
// drift is non-destructive, and skipping it would hide out-of-sync state.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// generatedSentinel marks a file this tool authored. The split tree — not root
// CHANGELOG.md — is canonical: root carries one released version block while the
// tree holds v1.0.0.md, v0.1.0.md and ~86 KB of unreleased entries that root
// CANNOT regenerate. So --emit may only mutate files it can prove it wrote;
// anything else is preserved and reported. Verify is deliberately NOT gated on
// this, because reporting drift is non-destructive and silence there would hide
// real out-of-sync state.
const generatedSentinel = "<!-- generated by tools/changelog-split -->"

// markGenerated appends the sentinel as a trailing comment, never on the first
// line: tools/changelog-lint requires every split file to open with a
// `# Changelog` heading.
func markGenerated(s string) string {
	return strings.TrimRight(s, "\n") + "\n\n" + generatedSentinel + "\n"
}

// ownedAndStale reports whether path is a regular file this tool authored that
// is absent from the current write set — the only kind of file it may delete.
func ownedAndStale(path string, writes map[string]string) bool {
	if _, keep := writes[path]; keep {
		return false
	}
	return fileHasSentinel(path)
}

// fileHasSentinel reports whether an existing regular file carries the
// generated marker. Unreadable paths and non-regular entries (a directory
// planted over a target) count as absent, so the caller's write still surfaces
// the real error instead of silently preserving it.
func fileHasSentinel(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(b), generatedSentinel)
}

// ownedOrAbsent allows the write: nothing there yet, or content this tool owns.
// A directory target is included so os.WriteFile still reports its error.
func ownedOrAbsent(path string) bool {
	if info, err := os.Stat(path); err != nil || !info.Mode().IsRegular() {
		return true
	}
	return fileHasSentinel(path)
}

var mRefRe = regexp.MustCompile(`\bM(\d{3,4})\b`)
var versionHeaderRe = regexp.MustCompile(`^## \[([^\]]+)\]\s*[—-]\s*(\d{4}-\d{2}-\d{2})\s*$`)

type versionBlock struct {
	Header string
	Tag    string
	Date   string
	Body   []string
}

type unreleasedChunk struct {
	Header string
	Body   []string
	Bucket string // current | m100-m199 | m1000+
}

type splitResult struct {
	Readme        string
	ReorgLog      string
	Current       string
	Buckets       map[string]string // path -> content
	Released      map[string]string // path -> content
	MainChangelog string
}

func main() {
	source := flag.String("source", "CHANGELOG.md", "source changelog file")
	outDir := flag.String("out-dir", "CHANGELOG", "output directory for split files")
	mainOut := flag.String("main-out", "", "path to write the rewritten root changelog when emitting (default: overwrite --source)")
	dryRun := flag.Bool("dry-run", false, "print the planned outputs without writing")
	emit := flag.Bool("emit", false, "write the generated files")
	verify := flag.Bool("verify", false, "compare generated files to --out-dir")
	force := flag.Bool("force", false, "on --emit, overwrite tree files this tool did not generate (still subject to the working-set loss gate)")
	discard := flag.Bool("discard-working-set", false, "on --emit, allow dropping working-set lines that appear in no generated output; a timestamped backup of unreleased/current.md is written first")
	flag.Parse()

	if !*dryRun && !*emit && !*verify {
		*dryRun = true
	}

	b, err := os.ReadFile(*source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "changelog-split: read %s: %v\n", *source, err)
		os.Exit(1)
	}
	res, err := buildSplit(string(b))
	if err != nil {
		fmt.Fprintf(os.Stderr, "changelog-split: %v\n", err)
		os.Exit(1)
	}

	if *dryRun {
		printPlan(res)
	}
	if *emit {
		rootTarget := *mainOut
		if strings.TrimSpace(rootTarget) == "" {
			rootTarget = *source
		}
		if err := writeResultForce(rootTarget, *outDir, res, *force, *discard); err != nil {
			fmt.Fprintf(os.Stderr, "changelog-split: emit: %v\n", err)
			os.Exit(1)
		}
	}
	if *verify {
		if err := verifyResult(*outDir, res); err != nil {
			fmt.Fprintf(os.Stderr, "changelog-split: verify: %v\n", err)
			os.Exit(1)
		}
	}
}

func buildSplit(src string) (splitResult, error) {
	lines := strings.Split(strings.ReplaceAll(src, "\r\n", "\n"), "\n")
	unreleasedIdx := -1
	var versions []versionBlock
	for i, line := range lines {
		if line == "## [Unreleased]" {
			unreleasedIdx = i
			continue
		}
		if m := versionHeaderRe.FindStringSubmatch(line); m != nil {
			versions = append(versions, versionBlock{Header: line, Tag: m[1], Date: m[2]})
		}
	}
	if unreleasedIdx < 0 {
		return splitResult{}, errors.New("missing `## [Unreleased]` header")
	}
	if len(versions) == 0 {
		return splitResult{}, errors.New("no released version blocks found")
	}

	// Find body ranges for released blocks. A body ends at the next `## ` header
	// of ANY kind, not merely the next version header or EOF: renderMain appends
	// a regenerated `## Releases` index after the last block, and under the old
	// EOF rule that index was swallowed into the final release's body and copied
	// into its tree file, so root never reached a fixed point.
	versionPositions := make([]int, 0, len(versions))
	sectionPositions := make([]int, 0, len(versions)+2)
	for i, line := range lines {
		if !strings.HasPrefix(line, "## ") {
			continue
		}
		sectionPositions = append(sectionPositions, i)
		if versionHeaderRe.MatchString(line) {
			versionPositions = append(versionPositions, i)
		}
	}
	for i := range versions {
		start := versionPositions[i] + 1
		end := len(lines)
		for _, p := range sectionPositions {
			if p >= start {
				end = p
				break
			}
		}
		versions[i].Body = trimTrailingBlankLines(lines[start:end])
	}

	unreleasedEnd := versionPositions[0]
	unreleasedBody := trimTrailingBlankLines(lines[unreleasedIdx+1 : unreleasedEnd])
	chunks := splitUnreleased(unreleasedBody)

	buckets := map[string][]unreleasedChunk{}
	for _, c := range chunks {
		buckets[c.Bucket] = append(buckets[c.Bucket], c)
	}

	// Declared releases are root's index entries that have no version block; their
	// tags and dates exist nowhere else, so the generated index files must name
	// them or those hand-written lines can never be reproduced.
	extra := extraReleases(versions, parseDeclaredReleases(lines))

	res := splitResult{
		Readme:        markGenerated(renderReadme(versions, buckets, extra)),
		ReorgLog:      markGenerated(renderReorgLog(versions, buckets, extra)),
		Current:       markGenerated(renderBucketDoc("current", buckets["current"])),
		Buckets:       map[string]string{},
		Released:      map[string]string{},
		MainChangelog: renderMain(lines[:unreleasedIdx], unreleasedBody, versions, extra),
	}
	for bucket, items := range buckets {
		if bucket == "current" {
			continue
		}
		res.Buckets[filepath.ToSlash(filepath.Join("unreleased", bucket+".md"))] = markGenerated(renderBucketDoc(bucket, items))
	}
	for _, v := range versions {
		res.Released[vFilename(v)] = markGenerated(renderVersion(v))
	}
	return res, nil
}

func splitUnreleased(body []string) []unreleasedChunk {
	var out []unreleasedChunk
	var cur *unreleasedChunk
	flush := func() {
		if cur == nil {
			return
		}
		cur.Body = trimTrailingBlankLines(cur.Body)
		cur.Bucket = bucketFor(cur.Header, cur.Body)
		out = append(out, *cur)
	}
	for _, line := range body {
		if strings.HasPrefix(line, "### ") {
			flush()
			cur = &unreleasedChunk{Header: line}
			continue
		}
		if cur == nil {
			cur = &unreleasedChunk{Header: "### Unclassified"}
		}
		cur.Body = append(cur.Body, line)
	}
	flush()
	return out
}

func bucketFor(header string, body []string) string {
	all := header + "\n" + strings.Join(body, "\n")
	matches := mRefRe.FindAllStringSubmatch(all, -1)
	if len(matches) == 0 {
		return "current"
	}
	min := 999999
	for _, m := range matches {
		var n int
		fmt.Sscanf(m[1], "%d", &n)
		if n < min {
			min = n
		}
	}
	if min >= 1000 {
		return "m1000+"
	}
	// The historical M600-M699 slice is much denser than its neighbors in the
	// current changelog. Split only that range into 50-wide buckets so the tree
	// stays readable without exploding the number of files elsewhere.
	if min >= 600 && min < 700 {
		start := (min / 50) * 50
		if start < 600 {
			start = 600
		}
		return fmt.Sprintf("m%d-m%d", start, start+49)
	}
	start := (min / 100) * 100
	if start < 100 {
		start = 100
	}
	return fmt.Sprintf("m%d-m%d", start, start+99)
}

// bucketNum extracts the milestone a bucket key names: "m100-m199" → 100,
// "m600-m649" → 600, "m1000+" → 1000. ok is false for keys that are not
// milestone buckets, such as "current".
func bucketNum(k string) (int, bool) {
	var n int
	if _, err := fmt.Sscanf(k, "m%d", &n); err != nil {
		return 0, false
	}
	return n, true
}

// bucketLess orders bucket keys by the milestone they name rather than by
// bytes. Bucket names are fixed-width only while every milestone is three
// digits: once the tree carries m1000+, byte order puts it BETWEEN m100-m199
// and m200-m299 ('-' < '0' at index 4, then '1' < '2'), so both generated
// indexes would mislead an operator scanning for where recent work landed.
// Non-milestone keys ("current") sort first, preserving their previous place.
func bucketLess(a, b string) bool {
	an, aOK := bucketNum(a)
	bn, bOK := bucketNum(b)
	switch {
	case aOK && bOK:
		if an != bn {
			return an < bn
		}
		return a < b // same starting milestone: deterministic tie-break
	case aOK:
		return false // milestone buckets sort after non-milestone keys
	case bOK:
		return true
	default:
		return a < b
	}
}

func renderBucketDoc(name string, chunks []unreleasedChunk) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Changelog — %s\n\n", name)
	if name == "current" {
		b.WriteString("This file holds the active `[Unreleased]` working set.\n\n")
	} else {
		b.WriteString("Historical slices extracted from the old `[Unreleased]` block.\n\n")
	}
	for i, c := range chunks {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(c.Header)
		b.WriteString("\n")
		if len(c.Body) > 0 {
			b.WriteString(strings.Join(c.Body, "\n"))
			b.WriteString("\n")
		}
	}
	return b.String()
}

func renderVersion(v versionBlock) string {
	var b strings.Builder
	b.WriteString("# Changelog\n\n")
	b.WriteString(v.Header)
	b.WriteString("\n\n")
	if len(v.Body) > 0 {
		b.WriteString(strings.Join(v.Body, "\n"))
		b.WriteString("\n")
	}
	return b.String()
}

func vFilename(v versionBlock) string {
	// `versionHeaderRe` captures the tag verbatim, and real changelogs use BOTH
	// forms — `## [1.0.0]` and `## [v1.1.0]` — while the split files on disk are
	// always `v<semver>.md`. Prefixing unconditionally doubled the letter for the
	// second form (`v1.1.0` → `vv1.1.0.md`), which made `--verify` report a
	// missing release file and would make `--emit` write that stray name while
	// removeStaleSplitFiles pruned the real `v1.1.0.md`.
	tag := v.Tag
	if len(tag) > 1 && (tag[0] == 'v' || tag[0] == 'V') {
		tag = tag[1:]
	}
	return fmt.Sprintf("v%s.md", tag)
}

// mainPointer is the sentence `changelog-lint` requires in root CHANGELOG.md.
const mainPointer = "See `CHANGELOG/unreleased/current.md` for the active working set and `CHANGELOG/` for historical milestone slices."

// dropLeadingBlanks normalises a body so re-parsing rendered output captures the
// same lines it emitted, which is what makes root a fixed point.
func dropLeadingBlanks(in []string) []string {
	for len(in) > 0 && strings.TrimSpace(in[0]) == "" {
		in = in[1:]
	}
	return in
}

// declaredRelease is one line of root's derived `## Releases` index, e.g.
// "- `v1.0.0.md` — `1.0.0` (2026-06-03)". The index is the ONLY place a release
// without a root version block has its tag and date recorded: v1.0.0.md and
// v0.1.0.md exist solely as tree files, so root carries their metadata and
// nothing parsed it. Reading it lets the generated README and reorg log name
// every release instead of just the one block root happens to hold, which is
// what makes those hand-written index lines reproducible.
type declaredRelease struct {
	file string
	tag  string
	date string
}

var releaseIndexRe = regexp.MustCompile("^- `([^`]+\\.md)` — `([^`]+)` \\(([^)]+)\\)$")

// parseDeclaredReleases reads the LAST `## Releases` section of root. Only that
// section is scanned, so a working-set bullet can never be mistaken for the index.
func parseDeclaredReleases(lines []string) []declaredRelease {
	start := -1
	for i, l := range lines {
		if strings.TrimRight(l, " \t") == "## Releases" {
			start = i
		}
	}
	if start < 0 {
		return nil
	}
	var out []declaredRelease
	for _, l := range lines[start+1:] {
		if strings.HasPrefix(l, "## ") {
			break
		}
		if m := releaseIndexRe.FindStringSubmatch(strings.TrimRight(l, " \t")); m != nil {
			out = append(out, declaredRelease{file: m[1], tag: m[2], date: m[3]})
		}
	}
	return out
}

// extraReleases returns the declared releases that no version block generates,
// in declaration order, deduped by file name. Matching is by file name rather
// than tag because tag style varies by hand ("1.1.0" vs "v1.1.0").
func extraReleases(versions []versionBlock, declared []declaredRelease) []declaredRelease {
	seen := make(map[string]bool, len(versions))
	for _, v := range versions {
		seen[vFilename(v)] = true
	}
	var out []declaredRelease
	for _, d := range declared {
		if seen[d.file] {
			continue
		}
		seen[d.file] = true
		out = append(out, d)
	}
	return out
}

// isDerivedIndex reports whether path is one of the two tree files that this
// tool generates in full -- renderReorgLog even writes "Generated by
// `tools/changelog-split`" into one of them. Their subsection counts are
// recomputed from the tree, so a stale count in an existing copy is derived
// bookkeeping, not content at risk, and guarding it would block ordinary
// adoption forever. No index FACT is lost by this exemption because the
// generators now emit every declared release; content files -- the working set,
// milestone buckets and released notes -- remain fully guarded.
func isDerivedIndex(outDir, path string) bool {
	rel, err := filepath.Rel(outDir, path)
	if err != nil {
		return false
	}
	switch filepath.ToSlash(rel) {
	case "README.md", "REORG-LOG.md":
		return true
	}
	return false
}

// renderMain rebuilds root CHANGELOG.md so that the tool can read its own output.
//
// It used to replace the Unreleased content and every released block with a
// pointer plus an index, but buildSplit requires at least one version block and
// takes the working set from root, so the rewritten file could not be re-read: a
// second --emit, or --verify after --emit, died with "no released version blocks
// found". Root is where a human authors notes, so it now round-trips: the working
// set and each released block are re-emitted verbatim, the pointer is added only
// when it is missing, and the index moves to the end because it is derived (and is
// excluded from every body by the section rule in buildSplit). The index also
// carries the declared releases root has no block for, so they survive the rewrite.
func renderMain(prefix, unreleased []string, versions []versionBlock, extra []declaredRelease) string {
	var b strings.Builder
	b.WriteString(strings.Join(trimTrailingBlankLines(prefix), "\n"))
	b.WriteString("\n\n## [Unreleased]\n\n")
	body := dropLeadingBlanks(trimTrailingBlankLines(unreleased))
	if !strings.Contains(strings.Join(body, "\n"), mainPointer) {
		b.WriteString(mainPointer + "\n\n")
	}
	if len(body) > 0 {
		b.WriteString(strings.Join(body, "\n"))
		b.WriteString("\n\n")
	}
	for _, v := range versions {
		b.WriteString(v.Header)
		b.WriteString("\n\n")
		if body := dropLeadingBlanks(v.Body); len(body) > 0 {
			b.WriteString(strings.Join(body, "\n"))
			b.WriteString("\n\n")
		}
	}
	b.WriteString("## Releases\n\n")
	b.WriteString("Released version notes live in per-version files under `CHANGELOG/`.\n\n")
	for _, v := range versions {
		fmt.Fprintf(&b, "- `%s` — `%s` (%s)\n", vFilename(v), v.Tag, v.Date)
	}
	// Re-emit the declared releases too: dropping them here would make the second
	// parse of the rewritten root lose their metadata, so the index files would
	// stop reproducing their own hand-held lines and root would not be a fixed
	// point.
	for _, d := range extra {
		fmt.Fprintf(&b, "- `%s` — `%s` (%s)\n", d.file, d.tag, d.date)
	}
	return b.String()
}

func renderReadme(versions []versionBlock, buckets map[string][]unreleasedChunk, extra []declaredRelease) string {
	var b strings.Builder
	b.WriteString("# Changelog\n\n")
	b.WriteString("This directory holds the split changelog structure.\n\n")
	b.WriteString("## Source of truth\n\n")
	b.WriteString("The files in this directory are canonical. Root `CHANGELOG.md` carries only one\n" +
		"released version block, while the tree holds every other release (`v1.0.0.md`, `v0.1.0.md`)\n" +
		"and all milestone slices, which root cannot regenerate. `tools/changelog-split --emit`\n" +
		"therefore refuses to overwrite or prune a file it did not generate (marked by a trailing\n" +
		"`generated by tools/changelog-split` comment); `--force` adopts them, and even then it never\n" +
		"deletes a file it did not author. `--force` also cannot discard the working set: dropping\n" +
		"lines that appear in no generated output needs `--discard-working-set`, which writes a\n" +
		"timestamped backup of `unreleased/current.md` first.\n\n")
	b.WriteString("## Layout\n\n")
	b.WriteString("- `unreleased/current.md` — active working set\n")
	keys := make([]string, 0, len(buckets))
	for k := range buckets {
		if k != "current" {
			keys = append(keys, k)
		}
	}
	sort.Slice(keys, func(i, j int) bool { return bucketLess(keys[i], keys[j]) })
	for _, k := range keys {
		fmt.Fprintf(&b, "- `unreleased/%s.md` — historical milestone slice\n", k)
	}
	for _, v := range versions {
		fmt.Fprintf(&b, "- `%s` — released version %s\n", vFilename(v), v.Tag)
	}
	for _, d := range extra {
		fmt.Fprintf(&b, "- `%s` — released version %s\n", d.file, d.tag)
	}
	b.WriteString("- `REORG-LOG.md` — reorg history\n")
	return b.String()
}

func renderReorgLog(versions []versionBlock, buckets map[string][]unreleasedChunk, extra []declaredRelease) string {
	var b strings.Builder
	b.WriteString("# Changelog Reorg Log\n\n")
	b.WriteString("Generated by `tools/changelog-split`.\n\n")
	b.WriteString("## Released versions\n\n")
	for _, v := range versions {
		fmt.Fprintf(&b, "- `%s` (%s)\n", v.Tag, v.Date)
	}
	for _, d := range extra {
		fmt.Fprintf(&b, "- `%s` (%s)\n", d.tag, d.date)
	}
	b.WriteString("\n## Unreleased slices\n\n")
	keys := make([]string, 0, len(buckets))
	for k := range buckets {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return bucketLess(keys[i], keys[j]) })
	for _, k := range keys {
		fmt.Fprintf(&b, "- `%s` — %d subsection(s)\n", k, len(buckets[k]))
	}
	return b.String()
}

// generatedLineIndex returns the set of non-blank trimmed lines that appear in
// at least one document this run generates: the working set, the regenerated
// root, every milestone bucket and every released version file.
//
// Counting lines rather than bytes is deliberate: a release slice legitimately
// SHRINKS current.md by moving `**M###**` chunks into milestone bucket files,
// and relocated content reappears in the generated buckets, so it is not a
// loss. Only content with nowhere to go counts. The generated root changelog is
// indexed too, because an operator may cut working-set entries straight into a
// new released version block.
func generatedLineIndex(res splitResult) map[string]bool {
	kept := map[string]bool{}
	index := func(doc string) {
		for _, l := range strings.Split(doc, "\n") {
			if t := strings.TrimSpace(l); t != "" {
				kept[t] = true
			}
		}
	}
	// Every generated document must be indexed, because every tree file the run
	// writes is now guarded. Omitting Readme/ReorgLog makes a tool-authored
	// README.md look entirely orphaned, which refused an ordinary re-emit and
	// broke emit idempotency.
	index(res.Current)
	index(res.MainChangelog)
	index(res.Readme)
	index(res.ReorgLog)
	for _, doc := range res.Buckets {
		index(doc)
	}
	for _, doc := range res.Released {
		index(doc)
	}
	return kept
}

// lostLines returns the non-blank trimmed lines of the existing file at path
// that appear in no generated output — precisely what overwriting that file
// would discard. A missing file loses nothing.
//
// This errs toward false refusals (a reflowed line reads as lost), which is the
// safe direction: a refusal destroys nothing and is overridable by flag.
func lostLines(path string, kept map[string]bool) ([]string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	var lost []string
	for _, l := range strings.Split(string(b), "\n") {
		if t := strings.TrimSpace(l); t != "" && !kept[t] {
			lost = append(lost, t)
		}
	}
	return lost, nil
}

// backupFile copies path to "<path>.bak-<UTC timestamp>" and returns the backup
// path, so content deliberately discarded under --discard-working-set stays
// restorable. The timestamp is second-granularity UTC: sortable, and distinct
// enough that repeated discards never overwrite each other's backup.
func backupFile(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	dest := path + ".bak-" + time.Now().UTC().Format("20060102T150405Z")
	if err := os.WriteFile(dest, b, 0o644); err != nil {
		return "", err
	}
	return dest, nil
}

// writeResultForce is the emit path, and it is non-destructive by default: a
// tree file the tool did not author is neither overwritten nor deleted, so an
// emit driven by a stub root cannot truncate current.md or prune v1.0.0.md /
// v0.1.0.md / the milestone buckets. The root changelog is the exception —
// maintaining that index IS the tool's job, and it is always written.
//
// With force=true it reclaims ownership of hand-held tree files, overwriting
// them (and marking them generated) so a later emit can maintain them. That is
// opt-in, but still not a licence to discard the canonical working set: the loss
// gate below refuses it unless discard=true, a separate opt-in, precisely because
// force alone read as "adopt" and silently truncated an 86 KB current.md down to
// a 288 byte stub.
//
// Tests call it through the writeResult wrapper in main_test.go, which pins both
// opt-ins to false.
func writeResultForce(mainPath, outDir string, res splitResult, force, discard bool) error {
	if err := os.MkdirAll(filepath.Join(outDir, "unreleased"), 0o755); err != nil {
		return err
	}
	writes := map[string]string{
		mainPath: res.MainChangelog,
	}
	skip := map[string]bool{}
	add := func(path, content string) {
		if !force && !ownedOrAbsent(path) {
			skip[path] = true
			fmt.Fprintf(os.Stderr, "changelog-split: preserving %s (not generated by this tool; use --force to adopt)\n", filepath.ToSlash(path))
			return
		}
		writes[path] = content
	}
	add(filepath.Join(outDir, "README.md"), res.Readme)
	add(filepath.Join(outDir, "REORG-LOG.md"), res.ReorgLog)
	add(filepath.Join(outDir, "unreleased", "current.md"), res.Current)
	for path, content := range res.Buckets {
		add(filepath.Join(outDir, filepath.FromSlash(path)), content)
	}
	for path, content := range res.Released {
		add(filepath.Join(outDir, filepath.FromSlash(path)), content)
	}
	if n := len(skip); n > 0 {
		fmt.Fprintf(os.Stderr, "changelog-split: preserved %d hand-held tree file(s); pass --force to adopt them\n", n)
	}
	// Tree loss gate. The ownership check above already shields hand-held files
	// from a DEFAULT emit; this gate is what remains once --force adopts them, so
	// it must guard EVERY tree file the run would overwrite, not just the working
	// set. The same line accounting already spans all generated output, and a
	// bucket or released file can be the only copy of its content too: a forced
	// emit that filed a working-set chunk into a hand-held bucket destroyed 1,704
	// unique lines while exiting 0. Root CHANGELOG.md is excluded -- regenerating
	// that index is the tool's job. Runs BEFORE the prune and BEFORE any write, so
	// a refused emit leaves the whole tree untouched.
	kept := generatedLineIndex(res)
	targets := make([]string, 0, len(writes))
	for path := range writes {
		if path == mainPath || isDerivedIndex(outDir, path) {
			continue
		}
		targets = append(targets, path)
	}
	sort.Strings(targets) // deterministic refusal order, like verifyResult
	for _, path := range targets {
		lost, err := lostLines(path, kept)
		if err != nil {
			return err
		}
		if len(lost) == 0 {
			continue
		}
		if !discard {
			return fmt.Errorf("refusing to shrink %s: %d line(s) appear in no generated output (first: %q) -- pass --discard-working-set to proceed (a timestamped backup is written first)",
				filepath.ToSlash(path), len(lost), lost[0])
		}
		bak, err := backupFile(path)
		if err != nil {
			return fmt.Errorf("backup %s: %w", filepath.ToSlash(path), err)
		}
		fmt.Fprintf(os.Stderr, "changelog-split: backing up %s to %s before discarding %d line(s)\n",
			filepath.ToSlash(path), filepath.ToSlash(bak), len(lost))
	}
	if err := removeStaleSplitFiles(outDir, writes); err != nil {
		return err
	}
	for path, content := range writes {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func removeStaleSplitFiles(outDir string, writes map[string]string) error {
	root := filepath.Clean(outDir)
	return filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if filepath.Ext(path) != ".md" {
			return nil
		}
		// Prune only this tool's own stale output. A same-named file it never
		// authored (v1.0.0.md, v0.1.0.md, a hand-held milestone bucket) is the
		// only copy of content root CHANGELOG.md cannot regenerate — deleting it
		// is the data loss this gate exists to prevent.
		if !ownedAndStale(path, writes) {
			return nil
		}
		return os.Remove(path)
	})
}

func verifyResult(outDir string, res splitResult) error {
	expected := map[string]string{
		filepath.Join(outDir, "README.md"):                res.Readme,
		filepath.Join(outDir, "REORG-LOG.md"):             res.ReorgLog,
		filepath.Join(outDir, "unreleased", "current.md"): res.Current,
	}
	for path, content := range res.Buckets {
		expected[filepath.Join(outDir, filepath.FromSlash(path))] = content
	}
	for path, content := range res.Released {
		expected[filepath.Join(outDir, filepath.FromSlash(path))] = content
	}
	// Deterministic report. Go randomises map iteration, so the old code listed
	// the same broken tree's problems in a different order on every run — noise
	// in CI logs and un-diffable gate output. Order by path, and print the slash
	// form so the message text is identical on Windows and POSIX rather than
	// merely self-consistent per platform.
	paths := make([]string, 0, len(expected))
	for path := range expected {
		paths = append(paths, path)
	}
	sort.Slice(paths, func(i, j int) bool {
		return filepath.ToSlash(paths[i]) < filepath.ToSlash(paths[j])
	})
	var bad []string
	for _, path := range paths {
		got, err := os.ReadFile(path)
		if err != nil {
			bad = append(bad, fmt.Sprintf("missing %s", filepath.ToSlash(path)))
			continue
		}
		if !bytes.Equal(got, []byte(expected[path])) {
			bad = append(bad, fmt.Sprintf("drift %s", filepath.ToSlash(path)))
		}
	}
	if len(bad) > 0 {
		return errors.New(strings.Join(bad, "; "))
	}
	return nil
}

func printPlan(res splitResult) {
	fmt.Println("changelog-split dry-run")
	fmt.Printf("  main: rewritten `CHANGELOG.md` with compact Unreleased pointer\n")
	fmt.Printf("  current: CHANGELOG/unreleased/current.md (%d bytes)\n", len(res.Current))
	keys := make([]string, 0, len(res.Buckets))
	for k := range res.Buckets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Printf("  bucket: CHANGELOG/%s (%d bytes)\n", k, len(res.Buckets[k]))
	}
	relKeys := make([]string, 0, len(res.Released))
	for k := range res.Released {
		relKeys = append(relKeys, k)
	}
	sort.Strings(relKeys)
	for _, k := range relKeys {
		fmt.Printf("  release: CHANGELOG/%s (%d bytes)\n", k, len(res.Released[k]))
	}
}

func trimTrailingBlankLines(in []string) []string {
	out := append([]string(nil), in...)
	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
		out = out[:len(out)-1]
	}
	return out
}
