// SPDX-License-Identifier: MIT

package main

// Durable tests for declared-release absorption.
//
// Root's `## Releases` index names every release the tree holds, but only one of
// them has a root version block, so the generated README and reorg log used to
// list a single release. The hand-written index lines for the others were then
// unique content: adopting those two files discarded them, which blocked
// `--emit --force` on any unadopted tree. renderReadme/renderReorgLog/renderMain
// now emit every declared release, so the lines are reproduced rather than
// dropped -- proven here WITHOUT relying on the derived-index gate exemption.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// declaredSample has one version block plus an index declaring three releases.
const declaredSample = `# Changelog

Intro line.

## [Unreleased]

### Added

- a working set entry

## [1.1.0] — 2026-09-01

### Added

- a released entry

## Releases

Released version notes live in per-version files under ` + "`CHANGELOG/`" + `.

- ` + "`v1.1.0.md`" + ` — ` + "`1.1.0`" + ` (2026-09-01)
- ` + "`v1.0.0.md`" + ` — ` + "`1.0.0`" + ` (2026-06-03)
- ` + "`v0.1.0.md`" + ` — ` + "`0.1.0`" + ` (2026-05-30)
`

func TestGeneratedIndexFilesNameDeclaredReleases(t *testing.T) {
	res, err := buildSplit(declaredSample)
	if err != nil {
		t.Fatalf("buildSplit: %v", err)
	}

	// Absorption, not exemption: the generated bytes must contain the lines.
	for _, want := range []string{
		"- `v1.0.0.md` — released version 1.0.0",
		"- `v0.1.0.md` — released version 0.1.0",
	} {
		if !strings.Contains(res.Readme, want) {
			t.Errorf("generated README.md missing declared release line %q\n%s", want, res.Readme)
		}
	}
	for _, want := range []string{
		"- `1.0.0` (2026-06-03)",
		"- `0.1.0` (2026-05-30)",
	} {
		if !strings.Contains(res.ReorgLog, want) {
			t.Errorf("generated REORG-LOG.md missing declared release line %q\n%s", want, res.ReorgLog)
		}
	}

	// The release that HAS a block must be listed once, not twice.
	if n := strings.Count(res.Readme, "- `v1.1.0.md` — released version 1.1.0"); n != 1 {
		t.Errorf("block-backed release duplicated in README: %d occurrences", n)
	}
	// Root must keep the metadata or the next parse loses it.
	for _, want := range []string{"`v1.0.0.md`", "`v0.1.0.md`"} {
		if !strings.Contains(res.MainChangelog, want) {
			t.Errorf("emitted root dropped declared index entry %s", want)
		}
	}
}

func TestDeclaredReleasesRoundTripIsStable(t *testing.T) {
	first, err := buildSplit(declaredSample)
	if err != nil {
		t.Fatalf("buildSplit: %v", err)
	}
	second, err := buildSplit(first.MainChangelog)
	if err != nil {
		t.Fatalf("re-parsing the emitted root: %v", err)
	}
	if second.Readme != first.Readme {
		t.Error("README.md is not a fixed point: declared releases were lost by the first emit")
	}
	if second.ReorgLog != first.ReorgLog {
		t.Error("REORG-LOG.md is not a fixed point: declared releases were lost by the first emit")
	}
	if second.MainChangelog != first.MainChangelog {
		t.Error("root CHANGELOG.md is not a fixed point after the index rewrite")
	}
}

// TestAdoptingDerivedIndexFilesNeedsNoDiscardFlag is the user-visible contract:
// adopting a hand-written README.md/REORG-LOG.md succeeds under --force alone.
func TestAdoptingDerivedIndexFilesNeedsNoDiscardFlag(t *testing.T) {
	res, err := buildSplit(declaredSample)
	if err != nil {
		t.Fatalf("buildSplit: %v", err)
	}
	dir := t.TempDir()
	out := filepath.Join(dir, "CHANGELOG")
	mainPath := filepath.Join(dir, "CHANGELOG.md")
	if err := writeResult(mainPath, out, res); err != nil {
		t.Fatalf("first emit: %v", err)
	}

	// Hand-write both index files with content the generator never emits, and
	// strip the ownership sentinel so they read as hand-held again.
	hand := "# Changelog\n\nThis directory holds the split changelog structure.\n\n## Layout\n\n- `unreleased/current.md` — active working set\n- `v1.0.0.md` — released version 1.0.0\n- `v0.1.0.md` — released version 0.1.0\n- `REORG-LOG.md` — reorg history\n"
	if err := os.WriteFile(filepath.Join(out, "README.md"), []byte(hand), 0o644); err != nil {
		t.Fatalf("plant README: %v", err)
	}
	reorg := "# Changelog Reorg Log\n\nGenerated by `tools/changelog-split`.\n\n## Released versions\n\n- `1.0.0` (2026-06-03)\n- `0.1.0` (2026-05-30)\n\n## Unreleased slices\n\n- `current` — 1 subsection(s)\n"
	if err := os.WriteFile(filepath.Join(out, "REORG-LOG.md"), []byte(reorg), 0o644); err != nil {
		t.Fatalf("plant REORG-LOG: %v", err)
	}

	if err := writeResultForce(mainPath, out, res, true, false); err != nil {
		t.Fatalf("adopting the derived index files must not need --discard-working-set: %v", err)
	}

	// The absorbed facts survived the adoption into generated bytes.
	got := mustRead(t, filepath.Join(out, "README.md"))
	for _, want := range []string{"- `v1.0.0.md` — released version 1.0.0", "- `v0.1.0.md` — released version 0.1.0"} {
		if !strings.Contains(got, want) {
			t.Errorf("adopted README.md dropped %q\n%s", want, got)
		}
	}
	gotReorg := mustRead(t, filepath.Join(out, "REORG-LOG.md"))
	for _, want := range []string{"- `1.0.0` (2026-06-03)", "- `0.1.0` (2026-05-30)"} {
		if !strings.Contains(gotReorg, want) {
			t.Errorf("adopted REORG-LOG.md dropped %q\n%s", want, gotReorg)
		}
	}
}
