// SPDX-License-Identifier: MIT

package main

// Safety tests for `--emit`: the tool must never destroy changelog content it
// does not own. Two destructive paths are covered — pruning a file that is not
// in the write set (removeStaleSplitFiles), and overwriting a larger hand-held
// file with a smaller generated one (writeResult).
//
// The split tree is canonical: root CHANGELOG.md carries exactly one released
// version block, yet the tree holds v1.0.0.md / v0.1.0.md and ~86 KB of
// unreleased entries in current.md that root CANNOT regenerate. An emit that
// prunes or truncates them destroys the only copy.

import (
	"os"
	"path/filepath"
	"testing"
)

// pointerSample mirrors the REAL root CHANGELOG.md: the Unreleased block is a
// pointer rather than content, and only one released version block is present.
const pointerSample = `# Changelog

Intro line.

## [Unreleased]

See CHANGELOG/unreleased/current.md for the active working set.

## [v1.1.0] — 2026-09-01

### Added
- released thing
`

// plantedTree lays down a split tree whose files are NOT generated by this tool
// (no sentinel), matching the state of the repository today.
func plantedTree(t *testing.T, out string) map[string]string {
	t.Helper()
	files := map[string]string{
		filepath.Join(out, "unreleased", "current.md"):   "# Changelog — current\n\nThis file holds the active `[Unreleased]` working set.\n\n### Fixed\n- hand-authored working set entry that MUST survive an emit\n",
		filepath.Join(out, "unreleased", "m100-m199.md"): "# Changelog — m100-m199\n\n### Added\n- **M145** tree-only history\n",
		filepath.Join(out, "unreleased", "m200-m299.md"): "# Changelog — m200-m299\n\n### Added\n- **M250** tree-only history\n",
		filepath.Join(out, "unreleased", "m300-m399.md"): "# Changelog — m300-m399\n\n### Added\n- **M350** tree-only history\n",
		filepath.Join(out, "unreleased", "m400-m499.md"): "# Changelog — m400-m499\n\n### Added\n- **M450** tree-only history\n",
		filepath.Join(out, "unreleased", "m500-m599.md"): "# Changelog — m500-m599\n\n### Added\n- **M550** tree-only history\n",
		filepath.Join(out, "unreleased", "m600-m649.md"): "# Changelog — m600-m649\n\n### Added\n- **M620** tree-only history\n",
		filepath.Join(out, "unreleased", "m650-m699.md"): "# Changelog — m650-m699\n\n### Added\n- **M680** tree-only history\n",
		filepath.Join(out, "unreleased", "m700-m799.md"): "# Changelog — m700-m799\n\n### Added\n- **M750** tree-only history\n",
		filepath.Join(out, "unreleased", "m800-m899.md"): "# Changelog — m800-m899\n\n### Added\n- **M850** tree-only history\n",
		filepath.Join(out, "unreleased", "m900-m999.md"): "# Changelog — m900-m999\n\n### Changed\n- **M923** tree-only history\n",
		filepath.Join(out, "v1.0.0.md"):                  "# Changelog\n\n## [1.0.0] — 2026-06-03\n\n### Added\n- content that root CHANGELOG.md cannot regenerate\n",
		filepath.Join(out, "v0.1.0.md"):                  "# Changelog\n\n## [0.1.0] — 2026-05-30\n\n### Added\n- content that root CHANGELOG.md cannot regenerate\n",
		filepath.Join(out, "README.md"):                  "# Changelog\n\nThis directory holds the split changelog structure.\n",
		filepath.Join(out, "REORG-LOG.md"):               "# Changelog Reorg Log\n\nHand-held reorg history.\n",
	}
	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("plant %s: %v", path, err)
		}
	}
	return files
}

func mustRead(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}

// TestEmitPreservesTreeOnlyFiles is the headline proof: an emit driven by a
// pointer-only root must not delete v1.0.0.md, v0.1.0.md or the milestone
// buckets, and must not truncate current.md.
func TestEmitPreservesTreeOnlyFiles(t *testing.T) {
	res, err := buildSplit(pointerSample)
	if err != nil {
		t.Fatalf("buildSplit: %v", err)
	}
	dir := t.TempDir()
	out := filepath.Join(dir, "CHANGELOG")
	want := plantedTree(t, out)

	if err := writeResult(filepath.Join(dir, "CHANGELOG.md"), out, res); err != nil {
		t.Fatalf("writeResult: %v", err)
	}

	for path, original := range want {
		got := mustRead(t, path)
		if got != original {
			t.Errorf("emit destroyed %s\n want original %d bytes, got %d bytes\n got: %.120q",
				path, len(original), len(got), got)
		}
	}
}

// TestPruneKeepsFilesTheToolDidNotGenerate proves removeStaleSplitFiles only
// deletes its own output: a stale bucket it generated before is pruned, while a
// same-named file it never authored is preserved.
func TestPruneKeepsFilesTheToolDidNotGenerate(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "CHANGELOG")
	if err := os.MkdirAll(filepath.Join(out, "unreleased"), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	foreign := filepath.Join(out, "unreleased", "m200-m299.md")
	if err := os.WriteFile(foreign, []byte("# Changelog — m200-m299\n\n### Added\n- hand-held\n"), 0o644); err != nil {
		t.Fatalf("write foreign: %v", err)
	}
	// Literal (not the constant) so this file compiles against the pre-fix tree.
	// It must match generatedSentinel in main.go.
	const sentinel = "<!-- generated by tools/changelog-split -->"
	owned := filepath.Join(out, "unreleased", "m300-m399.md")
	if err := os.WriteFile(owned, []byte("# Changelog — m300-m399\n\n### Added\n- generated earlier\n\n"+sentinel+"\n"), 0o644); err != nil {
		t.Fatalf("write owned: %v", err)
	}

	writes := map[string]string{} // nothing in the write set this round
	if err := removeStaleSplitFiles(out, writes); err != nil {
		t.Fatalf("removeStaleSplitFiles: %v", err)
	}
	if _, err := os.Stat(foreign); err != nil {
		t.Errorf("a file the tool never generated was deleted: %v", err)
	}
	if _, err := os.Stat(owned); !os.IsNotExist(err) {
		t.Errorf("a stale generated file should still be pruned, stat err=%v", err)
	}
}
