// SPDX-License-Identifier: MIT

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFirstSentence(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{"empty", "", ""},
		{"single sentence", "Package foo is the bar.", "Package foo is the bar."},
		{"two sentences", "Package foo is the bar. It also does baz.", "Package foo is the bar."},
		{"collapses whitespace", "  Package   foo.  ", "Package foo."},
		{"no period", "Package foo has no period", "Package foo has no period"},
		{"multi-line", "Package foo\ndoes bar and baz.", "Package foo does bar and baz."},
		{"period inside path", "uses kernel/agent.Tool interface (DECISIONS B0d).", "uses kernel/agent.Tool interface (DECISIONS B0d)."},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := firstSentence(c.in)
			if got != c.want {
				t.Errorf("firstSentence(%q) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}

func TestExtractGoDocSummary_FromDocGo(t *testing.T) {
	dir := t.TempDir()
	doc := "// Package widget is the canonical answer to everything.\npackage widget\n"
	if err := os.WriteFile(filepath.Join(dir, "doc.go"), []byte(doc), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := extractGoDocSummary(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "Package widget is the canonical answer to everything."
	if got != want {
		t.Errorf("extractGoDocSummary = %q, want %q", got, want)
	}
}

func TestExtractGoDocSummary_FallbackToFirstFile(t *testing.T) {
	dir := t.TempDir()
	// No doc.go — the tool should fall back to the first non-test
	// .go file in the directory.
	src := "// Package fallback returns the canonical thing.\npackage fallback\n"
	if err := os.WriteFile(filepath.Join(dir, "fallback.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "fallback_test.go"), []byte("package fallback"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := extractGoDocSummary(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(got, "Package fallback returns the canonical thing.") {
		t.Errorf("extractGoDocSummary = %q, want prefix %q", got, "Package fallback returns the canonical thing.")
	}
}

func TestExtractGoDocSummary_NoDocReturnsEmDash(t *testing.T) {
	dir := t.TempDir()
	// Package with no doc comment.
	src := "package nodoc\n"
	if err := os.WriteFile(filepath.Join(dir, "x.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := extractGoDocSummary(dir)
	if err != nil {
		t.Fatal(err)
	}
	if got != "—" {
		t.Errorf("extractGoDocSummary = %q, want %q", got, "—")
	}
}

func TestRenderGroup(t *testing.T) {
	pkgs := []pkgSummary{
		{RelDir: "kernel/agent", Summary: "The loop."},
		{RelDir: "kernel/bus", Summary: "The pub/sub."},
	}
	got := renderGroup("kernel", pkgs)
	for _, want := range []string{
		"# KERNEL",
		"auto-generated by tools/structure-md",
		"2 package(s):",
		"`kernel/agent`",
		"The loop.",
		"`kernel/bus`",
		"The pub/sub.",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("renderGroup missing %q in:\n%s", want, got)
		}
	}
}

func TestRun_GeneratesAndIsIdempotent(t *testing.T) {
	root := t.TempDir()
	// Lay out a tiny repo: one kernel package with doc.go.
	must := func(err error) { t.Helper(); if err != nil { t.Fatal(err) } }
	must(os.MkdirAll(filepath.Join(root, "kernel", "alpha"), 0o755))
	must(os.WriteFile(
		filepath.Join(root, "kernel", "alpha", "doc.go"),
		[]byte("// Package alpha is the test package.\npackage alpha\n"),
		0o644,
	))
	must(os.WriteFile(
		filepath.Join(root, "kernel", "alpha", "alpha.go"),
		[]byte("package alpha\n"),
		0o644,
	))

	out := filepath.Join(root, "out")
	if err := run(root, out, false); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(out, "STRUCTURE.kernel.md"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	got := string(data)
	if !strings.Contains(got, "`kernel/alpha`") {
		t.Errorf("expected kernel/alpha in output, got:\n%s", got)
	}
	if !strings.Contains(got, "Package alpha is the test package.") {
		t.Errorf("expected first sentence in output, got:\n%s", got)
	}
	// Re-run is idempotent: no error, no extra output, content
	// unchanged.
	if err := run(root, out, false); err != nil {
		t.Fatal(err)
	}
	data2, _ := os.ReadFile(filepath.Join(out, "STRUCTURE.kernel.md"))
	if string(data) != string(data2) {
		t.Errorf("second run produced different output")
	}
}
