// SPDX-License-Identifier: MIT

// Command jsonschemagen reads the Agezt wire contract (a JSONC file with
// embedded JSON Schema definitions) and emits Go types for the SDK.
//
// Source of truth: .project/agezt-contract.jsonc (per DECISIONS B0 and G2).
// This tool exists so SDK types are never hand-written and never drift from
// the contract. CI runs `make gen` and fails if the output differs from what
// is checked in.
//
// Scope (M0): the base schemas (Event, RegisterParams, Tool/Provider IO).
// As the contract grows append-only with new layers, the generator handles
// them automatically. Schemas it cannot map to a strict Go type yet emit
// `json.RawMessage` with a TODO comment so the build still succeeds.
//
// The generator uses only the standard library (POLICY §1).
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

func main() {
	in := flag.String("in", ".project/agezt-contract.jsonc", "input contract file (JSONC)")
	out := flag.String("out", "contract/gen/types.gen.go", "output Go file")
	pkg := flag.String("pkg", "gen", "output Go package name")
	flag.Parse()

	if err := run(*in, *out, *pkg); err != nil {
		fmt.Fprintf(os.Stderr, "jsonschemagen: %v\n", err)
		os.Exit(1)
	}
}

func run(inPath, outPath, pkgName string) error {
	raw, err := os.ReadFile(inPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", inPath, err)
	}

	stripped := stripJSONCComments(string(raw))

	// The contract file's top level is a bare "$schemas": { ... } pair.
	// Wrap it in braces to make a valid JSON object before parsing.
	wrapped := "{" + stripped + "}"

	var root struct {
		Schemas map[string]json.RawMessage `json:"$schemas"`
	}
	if err := json.Unmarshal([]byte(wrapped), &root); err != nil {
		return fmt.Errorf("parse contract: %w", err)
	}
	if len(root.Schemas) == 0 {
		return errors.New("contract has no $schemas block")
	}

	var buf bytes.Buffer
	writeHeader(&buf, pkgName, inPath)

	// Deterministic ordering for reproducible diffs.
	names := make([]string, 0, len(root.Schemas))
	for n := range root.Schemas {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, name := range names {
		var schema schemaNode
		if err := json.Unmarshal(root.Schemas[name], &schema); err != nil {
			return fmt.Errorf("schema %s: %w", name, err)
		}
		if err := emitSchema(&buf, name, schema); err != nil {
			return fmt.Errorf("emit %s: %w", name, err)
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// On format failure, write the unformatted source for debugging.
		_ = os.WriteFile(outPath+".unformatted", buf.Bytes(), 0o644)
		return fmt.Errorf("gofmt: %w (wrote unformatted to %s.unformatted)", err, outPath)
	}

	if err := os.MkdirAll(dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

func dir(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' || p[i] == '\\' {
			return p[:i]
		}
	}
	return "."
}

// schemaNode is the subset of JSON Schema this generator understands.
// Unknown fields are ignored; unknown shapes fall through to json.RawMessage.
type schemaNode struct {
	Type                 json.RawMessage            `json:"type"`
	Properties           map[string]json.RawMessage `json:"properties"`
	Required             []string                   `json:"required"`
	Items                json.RawMessage            `json:"items"`
	AdditionalProperties json.RawMessage            `json:"additionalProperties"`
	Ref                  string                     `json:"$ref"`
	Enum                 []json.RawMessage          `json:"enum"`
	Const                json.RawMessage            `json:"const"`
	Description          string                     `json:"description"`
}

// typeString returns the single "type" value, if the node has one.
// JSON Schema allows arrays of types; we only handle the single-type case
// (which covers all of the contract today).
func (s schemaNode) typeString() string {
	if len(s.Type) == 0 {
		return ""
	}
	var single string
	if err := json.Unmarshal(s.Type, &single); err == nil {
		return single
	}
	return "" // multi-type or non-string; fall through to interface{}
}

// writeHeader writes the file preamble: SPDX, "do not edit" notice, package
// clause, and imports.
func writeHeader(w io.Writer, pkg, source string) {
	fmt.Fprintf(w, "// SPDX-License-Identifier: MIT\n")
	fmt.Fprintf(w, "// Code generated by tools/jsonschemagen from %s. DO NOT EDIT.\n", source)
	fmt.Fprintf(w, "//\n")
	fmt.Fprintf(w, "// Per DECISIONS G2, SDK types are generated build-time from the JSON\n")
	fmt.Fprintf(w, "// Schema contract. Regenerate with `make gen`. CI verifies in sync.\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "package %s\n\n", pkg)
	fmt.Fprintf(w, "import \"encoding/json\"\n\n")
	// json may go unused if every emitted type is a plain alias; suppress
	// the unused-import error by referencing the package once.
	fmt.Fprintf(w, "// Ensure encoding/json is referenced even if no struct uses RawMessage.\n")
	fmt.Fprintf(w, "var _ = json.RawMessage(nil)\n\n")
}

func emitSchema(w io.Writer, name string, s schemaNode) error {
	if s.Description != "" {
		writeDocComment(w, name, s.Description)
	} else {
		fmt.Fprintf(w, "// %s is defined by the wire contract.\n", name)
	}

	switch s.typeString() {
	case "object":
		if len(s.Properties) > 0 {
			return emitStruct(w, name, s)
		}
		if len(s.AdditionalProperties) > 0 {
			vt, err := mapValueType(s.AdditionalProperties)
			if err != nil {
				return err
			}
			fmt.Fprintf(w, "type %s map[string]%s\n\n", name, vt)
			return nil
		}
		// Object with neither properties nor additionalProperties: opaque.
		fmt.Fprintf(w, "type %s map[string]json.RawMessage\n\n", name)
		return nil
	case "string":
		fmt.Fprintf(w, "type %s string\n\n", name)
		return nil
	case "integer":
		fmt.Fprintf(w, "type %s int64\n\n", name)
		return nil
	case "number":
		fmt.Fprintf(w, "type %s float64\n\n", name)
		return nil
	case "boolean":
		fmt.Fprintf(w, "type %s bool\n\n", name)
		return nil
	case "array":
		if len(s.Items) == 0 {
			fmt.Fprintf(w, "type %s []json.RawMessage\n\n", name)
			return nil
		}
		it, err := goTypeFromSchema(s.Items)
		if err != nil {
			return err
		}
		fmt.Fprintf(w, "type %s []%s\n\n", name, it)
		return nil
	}

	// $ref alias at the top level.
	if s.Ref != "" {
		fmt.Fprintf(w, "type %s = %s\n\n", name, refTypeName(s.Ref))
		return nil
	}

	// Fallback: opaque.
	fmt.Fprintf(w, "// TODO: jsonschemagen cannot yet map this shape; using opaque type.\n")
	fmt.Fprintf(w, "type %s json.RawMessage\n\n", name)
	return nil
}

func writeDocComment(w io.Writer, name, desc string) {
	desc = strings.TrimSpace(desc)
	if desc == "" {
		return
	}
	fmt.Fprintf(w, "// %s — %s\n", name, oneLine(desc))
}

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	return s
}

func emitStruct(w io.Writer, name string, s schemaNode) error {
	req := make(map[string]bool, len(s.Required))
	for _, r := range s.Required {
		req[r] = true
	}

	fieldNames := make([]string, 0, len(s.Properties))
	for n := range s.Properties {
		fieldNames = append(fieldNames, n)
	}
	sort.Strings(fieldNames) // deterministic

	fmt.Fprintf(w, "type %s struct {\n", name)
	for _, jsonName := range fieldNames {
		gt, err := goTypeFromSchema(s.Properties[jsonName])
		if err != nil {
			return fmt.Errorf("field %s.%s: %w", name, jsonName, err)
		}
		goName := exportedName(jsonName)
		tag := jsonName
		if !req[jsonName] {
			tag += ",omitempty"
		}
		fmt.Fprintf(w, "\t%s %s `json:\"%s\"`\n", goName, gt, tag)
	}
	fmt.Fprintf(w, "}\n\n")
	return nil
}

// goTypeFromSchema returns the Go type for an inline schema node, used by
// struct fields and array items.
func goTypeFromSchema(raw json.RawMessage) (string, error) {
	var s schemaNode
	if err := json.Unmarshal(raw, &s); err != nil {
		return "", err
	}
	if s.Ref != "" {
		return refTypeName(s.Ref), nil
	}
	switch s.typeString() {
	case "string":
		return "string", nil
	case "integer":
		return "int64", nil
	case "number":
		return "float64", nil
	case "boolean":
		return "bool", nil
	case "array":
		if len(s.Items) == 0 {
			return "[]json.RawMessage", nil
		}
		it, err := goTypeFromSchema(s.Items)
		if err != nil {
			return "", err
		}
		return "[]" + it, nil
	case "object":
		if len(s.AdditionalProperties) > 0 {
			vt, err := mapValueType(s.AdditionalProperties)
			if err != nil {
				return "", err
			}
			return "map[string]" + vt, nil
		}
		return "map[string]json.RawMessage", nil
	}
	// No discriminator we recognise — leave it opaque.
	return "json.RawMessage", nil
}

func mapValueType(raw json.RawMessage) (string, error) {
	// additionalProperties may be `true` (any) or a schema node.
	var b bool
	if err := json.Unmarshal(raw, &b); err == nil {
		return "json.RawMessage", nil
	}
	return goTypeFromSchema(raw)
}

func refTypeName(ref string) string {
	// "#/Foo" → "Foo".
	if i := strings.LastIndex(ref, "/"); i >= 0 {
		return ref[i+1:]
	}
	return ref
}

// exportedName converts a snake_case (or already-PascalCase) JSON name into
// an exported Go identifier with common initialism handling.
func exportedName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		up := strings.ToUpper(p)
		if _, ok := commonInitialisms[up]; ok {
			parts[i] = up
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// commonInitialisms is a small set of acronyms we want fully uppercased in
// Go identifiers (golint/staticcheck convention). Extend as the contract
// grows.
var commonInitialisms = map[string]struct{}{
	"ID":   {},
	"URL":  {},
	"URI":  {},
	"API":  {},
	"HTTP": {},
	"JSON": {},
	"TS":   {},
	"OS":   {},
	"IO":   {},
	"DB":   {},
	"RPC":  {},
	"SDK":  {},
	"UI":   {},
	"UUID": {},
	"ULID": {},
	"B64":  {},
	"AI":   {},
	"CPU":  {},
	"MS":   {},
}

// stripJSONCComments removes // line comments from a JSONC source while
// preserving comments inside string literals. Block comments (/* */) are not
// used in the contract and are intentionally not supported.
func stripJSONCComments(src string) string {
	var b strings.Builder
	b.Grow(len(src))

	inString := false
	escaped := false
	i := 0
	for i < len(src) {
		c := src[i]
		if inString {
			b.WriteByte(c)
			switch {
			case escaped:
				escaped = false
			case c == '\\':
				escaped = true
			case c == '"':
				inString = false
			}
			i++
			continue
		}
		if c == '"' {
			inString = true
			b.WriteByte(c)
			i++
			continue
		}
		// Outside string: look for "//"
		if c == '/' && i+1 < len(src) && src[i+1] == '/' {
			// Skip until newline.
			for i < len(src) && src[i] != '\n' {
				i++
			}
			// Keep the newline so line numbers in errors roughly track.
			continue
		}
		b.WriteByte(c)
		i++
	}
	return b.String()
}
