// SPDX-License-Identifier: MIT

package webui

import "embed"

// distFS holds the built React SPA (Vite output) that the daemon serves. The
// bundle is generated by `make frontend-build` (frontend/ → kernel/webui/dist)
// and committed, so `go build` works on a fresh checkout with no Node toolchain
// — go:embed is stdlib, so this adds zero Go dependencies. The `all:` prefix
// also embeds files Vite may emit with a leading dot/underscore.
//
//go:embed all:dist
var distFS embed.FS
